apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.secret_access_key
        - name: FACTSET_USER
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: factset.user
        - name: FACTSET_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: factset.key
        - name: FACTSET_FTP
          value: {{ .Values.env.FACTSET_FTP }}
        - name: FACTSET_RESOURCES
          value: {{ .Values.service.factsetresources }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel }}
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        # How does this work with no gtg? Can we just strip it out?
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumes:
        - name: factset-persistent
          persistentVolumeClaim:
            claimName: factset-reader-pvc

